<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260830103000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add user_avatar table for profile pictures.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE user_avatar (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, data BYTEA NOT NULL, mime_type VARCHAR(60) NOT NULL, byte_size INT NOT NULL, width INT NOT NULL, height INT NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_73256912A76ED395 ON user_avatar (user_id)');
        // ON DELETE CASCADE: the avatar is part of the account, so deleting the
        // account must take it with it. Nothing in PHP holds a reference to
        // this row from User, so the database is the only thing that can.
        $this->addSql('ALTER TABLE user_avatar ADD CONSTRAINT FK_73256912A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE user_avatar DROP CONSTRAINT FK_73256912A76ED395');
        $this->addSql('DROP TABLE user_avatar');
    }
}
