<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260903142031 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add admin_message table for admin-dashboard broadcasts (fanned out to per-user notifications at send time).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE admin_message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(120) NOT NULL, body TEXT NOT NULL, recipient_count INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, sent_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7281B2F6A45BB98C ON admin_message (sent_by_id)');
        $this->addSql('ALTER TABLE admin_message ADD CONSTRAINT FK_7281B2F6A45BB98C FOREIGN KEY (sent_by_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE admin_message DROP CONSTRAINT FK_7281B2F6A45BB98C');
        $this->addSql('DROP TABLE admin_message');
    }
}
